Sube1.HelloMVC/Models/Ders.cs
namespace Sube1.HelloMVC.Models
{
    public class Ders
    {
        public int Dersid { get; set; }
        public string Dersad { get; set; }
        public byte Kredi { get; set; }

    }
}

Sube1.HelloMVC/Models/ErrorViewModel.cs
namespace Sube1.HelloMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sube1.HelloMVC/Models/Ogrenci.cs
namespace Sube1.HelloMVC.Models
{
    public class Ogrenci : Object
    {
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int Numara { get; set; }

        //public override string ToString()
        //{
        //    return $"Ad:{Ad}-Soyad:{Soyad}-Numara:{Numara}";
        //}
    }
}

Sube1.HelloMVC/Models/Ogretmen.cs
namespace Sube1.HelloMVC.Models
{
    public class Ogretmen
    {
        public int Ogretmenid { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
    }
}

Sube1.HelloMVC/Models/ViewModels/OgrViewModel.cs
namespace Sube1.HelloMVC.Models.ViewModels
{
    public class OgrViewModel
    {
        public Ogrenci Ogrenci { get; set; }
        public Ogretmen Ogretmen { get; set; }
        public Ders Ders { get; set; }
    }
}

Sube1.HelloMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Sube1.HelloMVC.Models;
using System.Diagnostics;

namespace Sube1.HelloMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sube1.HelloMVC/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using Sube1.HelloMVC.Models;
using Sube1.HelloMVC.Models.ViewModels;

namespace Sube1.HelloMVC.Controllers
{
    public class OgrenciController : Controller
    {
        public ViewResult Index()//Action Metod
        {
            return View();
        }

        public ViewResult OgrenciDetay(int id)
        {
            var ogrt = new Ogretmen { Ad = "Osman", Soyad = "Yılmaz", Ogretmenid = 1 };

            Ogrenci ogr = null;
            if (id == 1)
            {
                ogr = new Ogrenci { Ad = "Ali", Soyad = "Veli", Numara = 123 };
            }
            else if (id == 2)
            {
                ogr = new Ogrenci { Ad = "Ahmet", Soyad = "Mehmet", Numara = 456 };
            }

            ViewData["ogrenci"] = ogr;
            ViewBag.student = ogr;
            ViewBag.teacher = ogrt;


            OgrViewModel vm = new OgrViewModel();
            vm.Ogretmen = ogrt;
            vm.Ogrenci = ogr;
            vm.Ders = new Ders { Dersid = 1, Dersad = "ProgTem", Kredi = 5 };

            return View(vm);
        }

        public ViewResult OgrenciListe()
        {
            var lst = new List<Ogrenci>();
            lst.Add(new Ogrenci { Ad = "Ali", Soyad = "Veli", Numara = 123 });
            lst.Add(new Ogrenci { Ad = "Ahmet", Soyad = "Mehmet", Numara = 456 });

            return View(lst);
        }
    }
}
//Controller'dan View'e Veri Taşıma Yöntemleri

//ViewData: Koleksiyon yapısıdır. Dictonary türünde koleksiyonlardır.
//Dictionary yapıları key-value pair'lerden oluşur.
//Keyler tekil olmalıdır.
//Keyler string, value'lar object türündedir.

//ViewBag: ViewData üstüne geliştirilmiş bir yapıdır. Arka planda ViewData koleksiyonunu kullanır.

//ViewModel

Sube1.HelloMVC/Controllers/OgretmenController.cs
using Microsoft.AspNetCore.Mvc;

namespace Sube1.HelloMVC.Controllers
{
    public class OgretmenController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }

        public ViewResult OgretmenListe()
        {
            return View();
        }
    }
}

Sube1.HelloMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Sube1.HelloMVC/Views/Ogrenci/Index.cshtml
@{
    ViewData["Title"] = "Öğrenci İşlemleri Ana Sayfası";
}


<h3>Öğrenci İşlemleri Ana Sayfası</h3>

Sube1.HelloMVC/Views/Ogrenci/OgrenciDetay.cshtml
@model OgrViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OgrenciDetay</title>
</head>
<body>   
    <h3>Öğrenci Detayları</h3>
    <h4>ViewData ile gelen öğrenci bilgileri</h4>
    @if (ViewData["ogrenci"] != null)
    {
        <p>Ad:@(((Ogrenci)ViewData["ogrenci"]).Ad)</p>
    }
    else
    {
        <p>Öğrenci Bulunamadı!</p>
    }

    <h4>ViewBag ile gelen öğrenci bilgileri</h4>
    @if (ViewBag.student != null)
    {
        <p>Ad:@ViewBag.student.Ad</p>
    }
    else
    {
        <p>Öğrenci Bulunamadı</p>
    }

    <h4>Viewbag ile gelen Öğretmen Bilgileri</h4>
    <p>@ViewBag.teacher.Ad</p>

    <h4>Model ile gelen öğrenci</h4>
    <p>
        @Model.Ogrenci.Ad
    </p>

    <h4>Model ile gelen öğretmen</h4>
    <p>
        @Model.Ogretmen.Ad
    </p>

    <h4>Model ile gelen Ders bilgisi</h4>
    <p>
        @Model.Ders.Dersad
    </p>
</body>
</html>

Sube1.HelloMVC/Views/Ogrenci/OgrenciListe.cshtml
@model List<Ogrenci>
@{
    ViewData["Title"] = "Öğrenci Listesi";
    ViewData["Desc"] = "Tüm okulda okuyan öğrencilerin listesi"; 

}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Numara</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Ad
                </td>
                <td>
                    @item.Soyad
                </td>
                <td>
                    @item.Numara
                </td>
            </tr>
        }
    </tbody>
</table>

Sube1.HelloMVC/Views/Ogretmen/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    Öğretmen Controller Index Cevabı
</body>
</html>

Sube1.HelloMVC/Views/Ogretmen/OgretmenListe.cshtml
@{
    ViewData["Title"] = "Ogretmen Listesi";
}

<h1>OgretmenListe</h1>

Sube1.HelloMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="@ViewData["Desc"]" />
    <title>@ViewData["Title"] - Sube1.HelloMVC</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sube1.HelloMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sube1.HelloMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Ogrenci/OgrenciListe">Öğrenci Listesi</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Öğrenci Listesi","OgrenciListe","Ogrenci",null,new{@class="nav-link text-dark"})
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-action="OgrenciListe" asp-controller="Ogrenci">Öğrenci Listesi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sube1.HelloMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>